spring.application.name=server
spring.datasource.url=jdbc:mysql://localhost:3306/clomi_db
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
groq.api.key=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
server.port=8080